# $FreeBSD: releng/9.3/sys/modules/toecore/Makefile 256109 2013-10-07 12:57:27Z pluknet $

.PATH: ${.CURDIR}/../../netinet

KMOD=	toecore
SRCS=	toecore.c
SRCS+=	opt_ofed.h opt_inet.h opt_inet6.h

.include <bsd.kmod.mk>
